public enum EventType {
  NONE,
  COMMAND_NEWGAME, //TODO new game / restart
  COMMAND_RESTART, 
  COMMAND_REPLAY, 
  NOTIFICATION_PLAYER_WON,
  NOTIFICATION_PLAYER_LOST,
  ROBOT_ACTION_COMPLETED
};

